### ISSUE TITLE
Drone.io CI/CD pipelines

### ISSUE THREAD

**Issue by itsdalmo** [itsdalmo/tf-modules#18]
Module for provisioning CI/CD pipelines. 

#### TODO: 

- [x] Add agents (workers).
- [x] Use Postgres backend (rds).
- [x] Set ingress using `allowed_cidr_blocks`.
- [x] Optional Route53 (to avoid circular dependency with GH Oauth).
- [x] If using Alias record, also use TLS terminated at the ALB (cert from ACM).
- [x] KMS encrypt the shared secret.
